baseURL = 'https://debuging-avi.com'
languageCode = 'en-us'
title = "Avi's Blog"
theme = 'ananke'

[ananke.social.follow]
new_window_icon = false
networks = [
  "linkedin",
  "github",
  "x-twitter"
]

[params.ananke.social.linkedin]
username = "tharwania"

[[ananke_socials]]
name = "x-twitter"
url = "https://x.com/aktharwani"